import Foundation

/// Only explicit overrides are stored. Unknown keys and repeated custom keys survive a round trip.
struct ConfigDocument: Codable, Equatable, Sendable {
    var overrides: [String: [String]] = [:]

    func values(_ key: String, catalog: ConfigCatalog = .shared) -> [String] {
        overrides[key] ?? RayonTerminalConfiguration.runtimeDefaults[key] ?? catalog.setting(key: key)?.defaultValue.values ?? []
    }
    func text(_ key: String) -> String { values(key).first ?? "" }

    mutating func set(_ key: String, _ values: [String], catalog: ConfigCatalog = .shared) {
        // Keep explicit intent, even when it equals Ghostty's default: Rayon has
        // legacy defaults (font size/thickening) that can differ from the catalog.
        // Export still removes default-valued entries; Reset removes the override.
        overrides[key] = values
    }

    /// Merge semantics match upstream: repeatable values replace, keybinds append, palette slots merge.
    mutating func merge(_ source: String, catalog: ConfigCatalog = .shared) throws {
        let source = try Self.decodeShareOrText(source)
        var incoming: [String: [String]] = [:]
        for (index, raw) in source.components(separatedBy: .newlines).enumerated() {
            let line = raw.trimmingCharacters(in: .whitespaces)
            if line.isEmpty || line.hasPrefix("#") { continue }
            guard let separator = line.firstIndex(of: "=") else {
                throw ConfigError.message("Line \(index + 1): expected key = value")
            }
            let key = String(line[..<separator]).trimmingCharacters(in: .whitespaces)
            guard !key.isEmpty, key.allSatisfy({ $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-") }) else {
                throw ConfigError.message("Line \(index + 1): invalid setting name")
            }
            var value = String(line[line.index(after: separator)...]).trimmingCharacters(in: .whitespaces)
            if ["background", "foreground", "cursor-color", "selection-background", "selection-foreground"].contains(key),
               value.count == 6, UInt32(value, radix: 16) != nil { value = "#" + value }
            if key == "palette" {
                guard let eq = value.firstIndex(of: "="), let slot = Int(value[..<eq]), (0...255).contains(slot),
                      !value[value.index(after: eq)...].isEmpty else {
                    throw ConfigError.message("Line \(index + 1): palette needs an index from 0 to 255 and a color")
                }
            }
            if catalog.setting(key: key)?.repeatable == true || catalog.setting(key: key) == nil {
                incoming[key, default: []].append(value)
            } else { incoming[key] = [value] }
        }
        // Commit only after every line parses, so a bad import cannot partially replace the draft.
        for (key, value) in incoming {
            if key == "palette" {
                var slots = paletteOverrides
                for item in value {
                    let parts = item.split(separator: "=", maxSplits: 1, omittingEmptySubsequences: false)
                    slots[Int(parts[0])!] = String(parts[1])
                }
                overrides[key] = slots.keys.sorted().map { "\($0)=\(slots[$0]!)" }
            } else if key == "keybind" {
                set(key, values(key, catalog: catalog) + value, catalog: catalog)
            } else { set(key, value, catalog: catalog) }
        }
    }

    var paletteOverrides: [Int: String] {
        var result: [Int: String] = [:]
        for item in overrides["palette"] ?? [] {
            let parts = item.split(separator: "=", maxSplits: 1, omittingEmptySubsequences: false)
            if parts.count == 2, let i = Int(parts[0]), (0...255).contains(i) { result[i] = String(parts[1]) }
        }
        return result
    }
    mutating func setPalette(_ index: Int, color: String?) {
        var slots = paletteOverrides
        slots[index] = color
        if slots.isEmpty { overrides.removeValue(forKey: "palette") }
        else { overrides["palette"] = slots.keys.sorted().map { "\($0)=\(slots[$0]!)" } }
    }

    func serialized(header: Bool = true, only keys: Set<String>? = nil) -> String {
        var lines = header ? ["# Config generated by Rayon · Ghostty Config", "# https://ghostty.zerebos.com", ""] : []
        for key in overrides.keys.sorted() where keys == nil || keys!.contains(key) {
            let defaults = ConfigCatalog.shared.setting(key: key)?.defaultValue.values ?? []
            if let setting = ConfigCatalog.shared.setting(key: key), overrides[key] == setting.defaultValue.values { continue }
            for value in overrides[key] ?? [] {
                if key == "keybind" && defaults.contains(value) { continue }
                if ConfigCatalog.shared.setting(key: key)?.repeatable == true && value.trimmingCharacters(in: .whitespaces).isEmpty { continue }
                if key == "palette" {
                    let p = value.split(separator: "=", maxSplits: 1)
                    if p.count == 2, let i = Int(p[0]), defaults.indices.contains(i), defaults[i] == p[1] { continue }
                }
                lines.append("\(key) = \(value)")
            }
        }
        return lines.joined(separator: "\n")
    }
    func shareURL(only keys: Set<String>? = nil) -> String? {
        let encoded = Data(serialized(header: false, only: keys).utf8).base64EncodedString()
            .replacingOccurrences(of: "+", with: "-").replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
        let url = "https://ghostty.zerebos.com/#share=" + encoded
        return url.count <= 1800 ? url : nil
    }
    static func decodeShareOrText(_ source: String) throws -> String {
        let trimmed = source.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.hasPrefix("https://") || trimmed.hasPrefix("http://") || trimmed.hasPrefix("#share=") else { return source }
        guard let payload = trimmed.components(separatedBy: "#").last?
            .components(separatedBy: "&").first(where: { $0.hasPrefix("share=") })?.dropFirst(6), !payload.isEmpty else {
            throw ConfigError.message("This URL does not contain a shared configuration")
        }
        var base64 = String(payload).removingPercentEncoding ?? String(payload)
        base64 = base64.replacingOccurrences(of: "-", with: "+").replacingOccurrences(of: "_", with: "/")
        base64 += String(repeating: "=", count: (4 - base64.count % 4) % 4)
        guard let data = Data(base64Encoded: base64), let decoded = String(data: data, encoding: .utf8) else {
            throw ConfigError.message("The shared configuration is not valid UTF-8 base64")
        }
        return decoded
    }

    func effectiveTheme(dark: Bool) -> ConfigTheme? {
        let raw = text("theme")
        var name = raw
        if raw.contains("light:") || raw.contains("dark:") {
            let prefix = dark ? "dark:" : "light:"
            name = raw.components(separatedBy: ",").map { $0.trimmingCharacters(in: .whitespaces) }
                .first(where: { $0.hasPrefix(prefix) }).map { String($0.dropFirst(prefix.count)) } ?? ""
        }
        return ConfigCatalog.shared.themes[name]
    }
    func effectiveColor(_ key: String, dark: Bool) -> String {
        var value = overrides[key]?.last ?? ""
        if value.isEmpty, let theme = effectiveTheme(dark: dark) { value = theme.entries.last(where: { $0.0 == key })?.1 ?? "" }
        if value.isEmpty { value = text(key) }
        if value == "cell-foreground" { return key == "foreground" ? "#ffffff" : effectiveColor("foreground", dark: dark) }
        if value == "cell-background" { return key == "background" ? "#000000" : effectiveColor("background", dark: dark) }
        if value.isEmpty {
            if ["cursor-color", "selection-background"].contains(key) { return effectiveColor("foreground", dark: dark) }
            if ["cursor-text", "selection-foreground"].contains(key) { return effectiveColor("background", dark: dark) }
        }
        return value
    }
    func effectivePalette(_ index: Int, dark: Bool) -> String {
        if let color = paletteOverrides[index] { return color }
        if let theme = effectiveTheme(dark: dark), theme.palette.indices.contains(index) { return theme.palette[index] }
        let colors = ConfigCatalog.shared.registry["palette"]!.defaultValue.values
        return colors.indices.contains(index) ? colors[index] : "#000000"
    }
}

enum ConfigError: LocalizedError {
    case message(String)
    var errorDescription: String? { if case let .message(s) = self { s } else { nil } }
}
